### ISSUE TITLE
Windows 11 address bar

### ISSUE THREAD

**Issue by TheDolphinSlayer** [krlvm/ClassicSearch#2]
First of all: Very grateful this is even an option at this point! But I was wondering if there was any chance of making the address bar height lower? I used the basic theme on Windows 11 for better comparison between the themes. If there isn't a way I understand, with the way microsoft is changing things, but was also curious if there was a way?
![image](https://user-images.githubusercontent.com/73983610/197873877-ceced424-96e6-4bd7-8bd9-17d29eb50763.png)

**Comment by krlvm** [comment]
Did you install Visual Studio Redistributable and ClassicSearch Hook DLLs?

**Comment by TheDolphinSlayer** [comment]
yea

**Comment by krlvm** [comment]
I don't think it is possible, unfortunately

**Comment by TheDolphinSlayer** [comment]
well thank you for trying, anyway! Still grateful this was even a possibility!

**Comment by mvildosolae** [comment]
To get the shorter address bar in Windows 11, you have to change the return value in this function to `-3`:

```
int WINAPI Patch_GetSystemMetricsForDpi(
    int  nIndex,
    UINT dpi
)
{
    if (nIndex == SM_CYFIXEDFRAME) return -3;
    return GetSystemMetricsForDpi(nIndex, dpi);
}
```

<img width="1024" height="768" alt="Image" src="https://github.com/user-attachments/assets/dcedeb6d-31a7-46be-b653-1622c2030e29" />
