### ISSUE TITLE
Windows 11: Control Panel doesn't launch

### ISSUE THREAD

**Issue by he3als** [krlvm/ClassicSearch#6]
With ClassicSearch installed on the current latest stable build of Windows 11 (22H2 22621.1265), Control Panel will not launch and will instantly close. It does not happen if I uninstall ClassicSearch.

**Comment by he3als** [comment]
https://user-images.githubusercontent.com/65787561/218884406-422a410a-c632-4c60-b308-1ae55a1cdca8.mp4

**Comment by krlvm** [comment]
Can you check if Open/Save dialogs in various programs work?

**Comment by he3als** [comment]
It doesn't crash or anything, but the search bar is not the correct height.

![explorer_hIvSB8lX8T](https://user-images.githubusercontent.com/65787561/219121716-5608cbc4-e562-43c0-be65-5d8a6a777000.png)

**Comment by krlvm** [comment]
Can you try to install ClassicSearch and then run `RestoreModernSearch-VARIANT.cmd`?

**Comment by he3als** [comment]
I do not have that script.

![explorer_XQzvvgYQqo](https://user-images.githubusercontent.com/65787561/221197267-35f7fb11-fd28-4bc3-91e0-e16d9e7933c7.png)

**Comment by krlvm** [comment]
I mean, VARIANT is AllUsers or CurrentUser depends on how you did install it.

**Comment by he3als** [comment]
Still doesn't seem to work.

**Comment by krlvm** [comment]
Fixed in [v1.0.1](https://github.com/krlvm/ClassicSearch/releases/tag/v1.0.1)
