### ISSUE TITLE
[Windows 10] A way to force the bigger/default address bar height

### ISSUE THREAD

**Issue by Tiagoquix** [krlvm/ClassicSearch#8]
Hello!

I want to disable the modern bar, but at the same time force the address bar to be wide (as is the default).

From what I understood by reading the project's README (and from other searches I did on the internet), if `GetSystemMetricsForDpi` returns `8` ([apparently the default value](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics)) as the result for `SM_CYFIXEDFRAME` the address bar becomes larger again.

I'm using ExplorerPatcher, but even checking and unchecking the "Shrink address bar height" option, the bar continues to shrink and doesn't change (as seen in the screenshot below).

![image](https://github.com/krlvm/ClassicSearch/assets/30274161/b97a73e2-6079-441e-b082-52787a85c3a8)

Trying to use ClassicSearch (installing, uninstalling etc.) also doesn't seem to fix my problem.

I know this may be a little outside the scope of the project, but is there a way to force the default behavior (i.e. return `7` to `SM_CYFIXEDFRAME` from `GetSystemMetricsForDpi`) while also keeping the modern search bar disabled?

I know that there is some kind of hook (`ep_hook` or something like that) in ExplorerPatcher to install add-ons in it, but I don't know the specific details and I don't know if it's needed.

I'm on Windows 10 Pro 22H2.

Thanks in advance.

**Comment by Tiagoquix** [comment]
@krlvm

**Comment by krlvm** [comment]
It's enough to execute only DisableModernSearch without installing the DLL.

> The distribution which can be downloaded from [Releases](https://github.com/krlvm/ClassicSearch/releases) includes the batch files for installation or disabling the modern search:
>>INSTALL.cmd - install DLL for reducing address bar height and turn off modern search experience
UNINSTALL.cmd - install DLL for reducing address bar height and restore modern search experience
**DisableModernSearch-CurrentUser.cmd - disable modern search experience for current user**
RestoreModernSearch-CurrentUser.cmd - restore modern search experience for current user
**DisableModernSearch-AllUsers.cmd - disable modern search experience for current user**
RestoreModernSearch-AllUsers.cmd - restore modern search experience for current user

**Comment by Tiagoquix** [comment]
@krlvm The problem is that there is something on my PC that I don't know what makes the address bar smaller (like before the 2004 update), so I would kindly like there to be some way to **force** the default behavior with the use of this script (if possible, of course).

Thanks in advance.

**Comment by krlvm** [comment]
If you previously used ClassicSearch, then you need to run UNINSTALL first, reboot and run DisableModernSearch then.

**Comment by Torinde** [comment]
I don't use any special Search or ExplorerPatcher or any other similar tweaking tools. I didn't do any change, except Windows updates.

Recently the address bar in File explorer shrank in height. It was higher (top in below screenshot) and now it's lower:
![image](https://github.com/krlvm/ClassicSearch/assets/97228894/72257261-0724-4174-ad99-291b06a610c6)
([source](https://www.reddit.com/r/Windows10/comments/jv4glr/windows_explorer_address_bar_search_bar_height/?rdt=48604))

Any ideas how to restore the height? Is there a registry setting for that?

**Comment by krlvm** [comment]
Looks like they disabled the "modern" search.
If you want to make it big again, rebuild ClassicSearch DLL replacing 0 with 8 [here](https://github.com/krlvm/ClassicSearch/blob/4bfea3b82eb4c917f5641a5dbf3deff844c10bdf/ClassicSearch/dllmain.c#L93)

**Comment by krlvm** [comment]
As people say, you can also re-enable feature `18755234` with ViveTool.

**Comment by Torinde** [comment]
It worked, thank you!

**Comment by M4tEd** [comment]
> Looks like they disabled the "modern" search. If you want to make it big again, rebuild ClassicSearch DLL replacing 0 with 8 [here](https://github.com/krlvm/ClassicSearch/blob/4bfea3b82eb4c917f5641a5dbf3deff844c10bdf/ClassicSearch/dllmain.c#L93)

I get the issue that ClassicSearch64.dll is not a valid Win32 application and I can't find the line that's responsible for using the 32 ver instead of 64 (I even put the 32 bit version there, it still didn't work). If it's not a bother could you push the code that makes the address big?

**Comment by krlvm** [comment]
You should not launch the DLLs, build both 32- and 64-bit versions (in Release), put artifacts to installer and install them

**Comment by Tiagoquix** [comment]
For anyone who may have stumbled upon this after searching the internet, here is a quick tutorial on how to solve the problem:

- [Download the latest version of ViVeTool.](https://github.com/thebookisclosed/ViVe/releases/latest)
- Extract the files from the downloaded ZIP to a folder.
- Open the folder with the extracted files and copy its complete directory path from the address bar.
- Open Command Prompt as administrator and type `cd /d "[press CTRL+V here]"` and press Enter to navigate to the extracted folder.
- Type `ViVeTool.exe /enable /id:18755234` and press Enter. Done.

**Comment by M4tEd** [comment]
Thank you, your method worked!

May you also know how to fix the search bar? It looks asymmetrical and uses the old/new UI for selecting the history. Before this you could see up to 6 history items and could even delete the history searches but this one doesn't allow for that. I attached the image as reference.
![image](https://github.com/krlvm/ClassicSearch/assets/119826524/46228f3b-4634-4b88-95cb-b680256078e0)

**Comment by Tiagoquix** [comment]
> Thank you, your method worked!
> 
> May you also know how to fix the search bar? It looks asymmetrical and uses the old/new UI for selecting the history. Before this you could see up to 6 history items and could even delete the history searches but this one doesn't allow for that. I attached the image as reference. ![image](https://private-user-images.githubusercontent.com/119826524/292777701-46228f3b-4634-4b88-95cb-b680256078e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NDg5MzEsIm5iZiI6MTcwMzU0ODYzMSwicGF0aCI6Ii8xMTk4MjY1MjQvMjkyNzc3NzAxLTQ2MjI4ZjNiLTQ2MzQtNGI4OC05NWNiLWI2ODAyNTYwNzhlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQyMzU3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjE2ODEzMjk2MjY2NTUyOWRlYmIzNmE4M2Y3MTE5OWFiNGI1MTg1ZTRmOWJmMjQzZWNmZDE3ZmQ1MTViZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.knlISytwJ3hfcrInQHmNFcH3H5OtY098UXQzAalc3dc)

Try https://winaero.com/restore-classic-search-in-file-explorer-in-windows-10-version-1909/ (I would recommend doing it via the Winaero Tweaker program) and enabling "Disable modern search bar" under "File Explorer" options in ExplorerPatcher. Then, reapply the tweak from ViVeTool and restart your PC. For me, I have both the classic search + the bigger size for both the address bar and the search bar.

**Comment by Tiagoquix** [comment]
https://winaero.com/disable-web-search-in-windows-10-taskbar/ may help too (it's available in the Winaero Tweaker program).

**Comment by weiqi-chen** [comment]
`ViVeTool.exe /enable /id:18755234` First, then "Enable Classic Search" in File Explorer by Winaero Tweaker.
You get bigger/default address bar height and A Classic Search.
