### ISSUE TITLE
How to compile your custom DLL (ClassicSearch directory)?

### ISSUE THREAD

**Issue by razorzinho** [krlvm/ClassicSearch#9]
I've been trying to compile your DLL **with and without** changes on it, and it keeps giving me some errors. Could you provide information on what requirements I should fulfill to compile it?

Like this one:
```
ccTKuGkL.o:dllmain.c:(.text+0x96): undefined reference to `PatchIAT'
collect2.exe: error: ld returned 1 exit status
```

and the errors in the image below:
![image](https://github.com/krlvm/ClassicSearch/assets/64384760/85b50022-3479-4ad5-9793-10bce0004649)

I've had these issues by using `gcc.exe -shared -o ClassicSearch64.dll "ClassicSearch/dllmain.c"`

Thanks in advance!

**Comment by krlvm** [comment]
I build it with MSVC, but you're just missing a type cast - read the compilation log carefully:
![image](https://github.com/krlvm/ClassicSearch/assets/51774833/dac38caf-c035-45d5-a5cb-662a2f370423)

**Comment by razorzinho** [comment]
This doesn't seem to be correct. I've cloned the repo again and tried compiling it from your fresh downloaded source code. Still, I get the following errors:

![image](https://github.com/krlvm/ClassicSearch/assets/64384760/4db7b176-75d3-474f-80e9-2e958a2dd898)

This is the attempt to compile the dll with `gcc -c dllmain.c`. Since it's giving me those errors with NO MODIFICATIONS in the code, it should be something you messed up. Could you try and take a look at it?

**Comment by krlvm** [comment]
As I see, it was resolving `uintptr_t` properly initially, what did you change?
It builds with MSVC without any problem.
